import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import "./css/homepage.css"
import AnimatedComponent from "./components/AnimatedComponent";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "maimai中国玩家站",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://chinese-fonts-cdn.deno.dev/packages/dymh/dist/DouyinSansBold/result.css"
        />
      </Head>
      <body className="font-douyin">
        <AnimatedComponent>
          <div className="relative">
            {/* Top Container Back */}
            <div className="absolute inset-0 z-[-1] flex justify-center ">
              <div className="w-[900px] h-[500px] bg-[url('/img/aurora.png')] bg-no-repeat bg-contain"></div>
            </div>
            {/* Top Container */}
            <div className="relative z-[10] w-[90%] max-w-[800px] bg-white/30 backdrop-blur-md shadow-lg rounded-lg p-6 mx-auto mt-10 flex items-center space-x-4 justify-center
          text-2xl  text-white font-bold">
              <Link href={"/"} className="hover:scale-125 transition-all duration-300 ease-in-out">主页</Link>
              <div>|</div>
              <Link href={"/music"} className="hover:scale-125 transition-all duration-300 ease-in-out">音乐</Link>
              <div>|</div>
              <Link href={"/region"} className="hover:scale-125 transition-all duration-300 ease-in-out">区域</Link>
              <div>|</div>
              <Link href={"/"} className="hover:scale-125 transition-all duration-300 ease-in-out">工具</Link>
              <div>|</div>
              <Link href={"/"} className="hover:scale-125 transition-all duration-300 ease-in-out">教学</Link>
            </div>
          </div>

          {children}

        </AnimatedComponent>
      </body>
    </html>
  );
}
