import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import "./css/homepage.css"
import AnimatedComponent from "./components/AnimatedComponent";
import Link from "next/link";
import UserLogin from "./components/UserLogin";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "maimai中国玩家站",
  description: "Generated by create next app",
  referrer: 'no-referrer',
};


function StarMove({ count = 5 }) {
  // 生成均匀分布的水平位置
  const generateEvenlyDistributedPositions = (count: number) => {
    const step = 100 / count; // 将屏幕宽度按元素数量等分 (百分比)
    return Array.from({ length: count }).map((_, index) => {
      const base = index * step; // 每个区间的起点
      const randomOffset = Math.random() * step * 0.8; // 在区间内偏移 (80% 范围)
      return base + randomOffset; // 确保值分布在 [base, base + step*0.8]
    });
  };

  const positions = generateEvenlyDistributedPositions(count);

  return (
    <>
      {positions.map((startLeft, index) => {
        const startTop = Math.random() * 5; // 随机起始高度 (0% ~ 5%)

        const style = {
          top: `${startTop}vh`, // 随机起始高度
          left: `${startLeft}vw`, // 均匀分布的水平位置
        };

        return (
          <div
            key={index}
            style={style}
            className="fixed w-[200px] h-[150px] bg-[url('/img/tail.png')] bg-no-repeat bg-contain z-[-2] animate-moveStar"
          ></div>
        );
      })}
    </>
  );
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let token = ""
  const textstroke = {
    textShadow: '-2px -2px 2px rgba(255, 255, 255, 1), 2px -2px 2px rgba(255, 255, 255, 1), -2px 2px 2px rgba(255, 255, 255, 1), 2px 2px 2px rgba(255, 255, 255, 1)'
  };
  const textDonate = {
    textShadow: '-2px -2px 4px rgba(128, 90, 213, 1), 2px -2px 4px rgba(128, 90, 213, 1), -2px 2px 2px rgba(128, 90, 213, 1), 2px 2px 2px rgba(128, 90, 213, 1)'
  };


  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://chinese-fonts-cdn.deno.dev/packages/dymh/dist/DouyinSansBold/result.css"
        />
      </Head>
      <body className="font-douyin">
        <div className="relative h-screen overflow-scroll">
          <Link href={'/tool/donate'} className="fixed z-[5] bottom-5 right-5 flex flex-col justify-center items-center hover:cursor-pointer transition-all duration-300 hover:bottom-8"><img src="/img/youxibi.png" className="hover:scale-105 transition-all duration-300 ease-in-out" alt="" /><h1 className="text-white font-bold" style={textDonate}>请开发者打一把mai</h1></Link>
          <Link href={'/tool/feedback'} className="fixed z-[5] bottom-5 left-5 flex flex-col justify-center items-center hover:cursor-pointer transition-all duration-300 hover:bottom-8"><img src="/img/yijianfankui.png" className="hover:scale-105 transition-all duration-300 ease-in-out" alt="" /><h1 className="text-white font-bold" style={textDonate}>意见反馈</h1></Link>
          <AnimatedComponent isVisible={true}>
            {/* BackGround Layer */}
            <div className="fixed top-0 left-0 w-full h-full  z-[-1] bg-[url('/img/bg_shines.png')]">
            </div>
            <div className="fixed top-0 left-0 w-full h-full  z-[-2]">
              <div className="w-[10px] h-[200px]">
              </div>
              <div className="flex justify-center max-sm:hidden max-md:hidden max-lg:hidden max-xl:hidden">
                <div className="w-[1000px] h-[600px] max-xl:h-[400px] max-xl:w-[300px]  bg-[url('/img/chara-left.png')] bg-no-repeat bg-contain bg-left "></div>
                <div className="relative w-[1200px] h-[500px] flex justify-center items-center space-x-10">
                  <img src="/img/front_left.png" className="absolute -left-20 w-[400px] z-[1]" alt="" />
                  <img src="/img/rainbow.png" className="absolute top-0 w-[600px] z-[-1]" alt="" />
                  <img src="/img/front_right.png" className="absolute -right-28 w-[400px] z-[1]" alt="" />
                </div>
                <div className="w-[1000px] h-[600px] max-xl:h-[400px] max-xl:w-[300px] bg-[url('/img/chara-right.png')] bg-no-repeat bg-contain bg-right"></div>
              </div>
            </div>
            <StarMove />
            <div className="fixed w-full h-full mt-[-80px] bg-[url('/img/bg_pattern.png')] z-[-3] animate-moveDot"></div>
            <div className="relative">
              {/* Top Container Back */}
              <div className="absolute inset-0 z-[-1] flex justify-center ">
                <div className="max-sm:w-[600px] w-[900px] h-[500px] bg-[url('/img/aurora.png')] bg-no-repeat bg-contain"></div>
              </div>
              {/* Top Container */}
              <div className="relative z-[10] w-[90%] max-w-[800px] bg-white/30 backdrop-blur-md shadow-lg rounded-lg p-6 mx-auto mt-10 flex items-center space-x-4 justify-center
          text-2xl  text-white font-bold">
                <Link href={"/music"} className="hover:scale-125 transition-all duration-300 ease-in-out text-blue-500" style={textstroke}>音乐</Link>
                <div>|</div>
                <Link href={"/region"} className="hover:scale-125 transition-all duration-300 ease-in-out text-blue-500" style={textstroke}>区域</Link>
                <div>|</div>
                <Link href={"/tool"} className="hover:scale-125 transition-all duration-300 ease-in-out text-blue-500" style={textstroke}>工具</Link>
                <div>|</div>
                <Link href={"/guide"} className="hover:scale-125 transition-all duration-300 ease-in-out text-blue-500" style={textstroke}>教学</Link>
              </div>
            </div>
            {children}
            <Link href={"/"} className="top-4 left-4 size-44">
              <div className="fixed top-4 left-4 size-44 bg-[url('/img/moon.png')] bg-contain flex justify-center items-center hover:scale-105 transition-all duration-300 ease-in-out">
                <img src="/img/logo.png" alt="" />
              </div>
            </Link>
            <UserLogin />
          </AnimatedComponent>
        </div>
      </body>
    </html>
  );
}
