name: Deploy on Push to dev

on:
  push:
    branches:
      - dev  # 当 dev 分支收到推送时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print the ref value (for debugging)
        run: |
          echo "The ref is: $GITHUB_REF"

      - name: Trigger Webhook for Deployment
        run: |
          curl -X POST http://154.37.213.44:88/webhook \
            -H "Content-Type: application/json" \
            -d '{"ref": "${{ github.ref }}"}'