name: Deploy on Push to dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Webhook for Deployment
        run: |
          set -e
          JSON=$(jq -n --arg ref "$GITHUB_REF" --arg repo "$GITHUB_REPOSITORY" '{ref: $ref, repository: $repo}')
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d "$JSON")
          if [ "$response" != "200" ]; then
            echo "部署失败，状态码: $response"
            exit 1
          fi
